version : "3.9"

services:    
    web:
        image: nginx:1.23.4         # always try to download a specific version
        volumes:
            - ./templates:/etc/nginx/templates
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80         # since https requests come on port 80