version : "3.9"

services:
    dotnet_api:
        build: ./
        image: dotnet_api
        ports:
            - "5001:5001" ## map local 8080 to containor port 80
        restart: always
        environment:
            - ASPNETCORE_HTTP_PORT=https://+:5001
            - ASPNETCORE_URLS=http://+:5000
